version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "TheSander562"
    assignees:
      - "TheSander562"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    groups:
      patch-updates:
        update-types: ["patch"]
      minor-updates:
        update-types: ["minor"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "TheSander562"
    assignees:
      - "TheSander562"
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      github-actions:
        patterns:
          - "*"
